### PR TITLE
WIP how to handle People on the home page. 

### PR DESCRIPTION
**Pull request by harperreed**
We need a way to feature leads, working group leads and volunteers.

### CODE REVIEW

**Comment by kreativmonkey** [comment]
i have some ideas to improve the design of this section, especially the section with the links to social platforms, while using icon fonts for display. But I can't do that until tomorrow during the day (german time)

**Comment by harperreed** [comment]
do you have a preferred icon font pack? I was thinking the same thing

**Comment by kreativmonkey** [comment]
Fontawesome ore Ionicon (https://ionicons.com/) are great choices.

**Comment by harperreed** [comment]
Needs a bit of work - but is a decent start. 

passing off to you @kreativmonkey

**Comment by kreativmonkey** [comment]
I have looked at the changes and made some improvements. If you like them, please merge @harperreed

**Comment by harperreed** [comment]
I think the social icons are colliding. Should we add some space?

**Pull request merged**
